version: "3"
 
services:
  database:
    image: oracle/database:19.3.0-ee
    container_name: oracle19c
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      ORACLE_PDB: orcl
      ORACLE_PWD: password
      CONTAINER_NAME: orcl
    volumes:
      - ~/workspace/spatial/tmp/oracle/oradata:/opt/oracle/oradata
      - ~/workspace/spatial/docker/oracle/scripts:/opt/oracle/scripts/setup
