version: '3.4'
services:
  db:
    image: mysql
    restart: always    
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - ./data/:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/data.sql
    expose:
        - "3306"
    ports:
        - "3306:3306"
